title: Omar-Mohammed
description: PhD in machine learning, working on deep neural networks and evoluationary optimization
google_analytics:
show_downloads:
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
